// flow-typed signature: 27a90bd3fe2c7d4106f5fea55bcc5268
// flow-typed version: <<STUB>>/eslint-import-resolver-webpack_v^0.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-webpack/resolve-alias' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-webpack/index' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack'>;
}
declare module 'eslint-import-resolver-webpack/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack'>;
}
declare module 'eslint-import-resolver-webpack/resolve-alias.js' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack/resolve-alias'>;
}
